language: c++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++

before_install:
  - brew update
  - brew install pyenv
  - eval "$(pyenv init -)"
  - pyenv install 2.7.6
  - pyenv global 2.7.6
  - pyenv rehash
  - pip install cpp-coveralls
  - pyenv rehash
script:
    - cd tests
    - g++ --version
    - ./run_tests.sh
after_success:
    - coveralls
