language: c++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++

before_install:
  - pip install cpp-coveralls
script:
    - cd tests
    - g++ --version
    - ./run_tests.sh
after_success:
    - coveralls
