language: c++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++
script:
    - cd tests
    - alias g++='g++ -std=c++11'
    - g++ --version
    - ./run_tests.sh
