name: DTW_cpp ci

on:
  push:
  schedule:
    # Run tests every saturday
    - cron:  '* * * * */6'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install gcovr
    - name: Run tests
      run: |
        g++ --version
        ./run_tests.sh
    - name: Generate coverage
      run: |
        gcovr -r . --xml > coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true