name: DTW_cpp ci

on:
  push:
  schedule:
    # Run tests every saturday
    - cron:  '* * * * */6'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        g++ --version
        ./run_tests.sh